apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: memcached-hpa
spec:
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  scaleTargetRef:
    apiVersion: cache.example.com/v1
    kind: Memcached
    name: memcached-sample